FROM 763104351884.dkr.ecr.eu-central-1.amazonaws.com/tensorflow-training:2.3.1-gpu-py37-cu110-ubuntu18.04

COPY ./NLP/src /src

WORKDIR /src

RUN pip install -r requirements.txt

ENV PYTHONPATH='/src/:$PYTHONPATH'

ENTRYPOINT ["python","-m" , "src.train"]