name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build and push cpu
        id: docker_build_cpu
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./NLP/Dockerfile.cpu
          push: true
          tags: torlof/nlp-cpu-docker-keras:latest
      
      - name: Build and push gpu
        id: docker_build_gpu
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./NLP/Dockerfile.gpu
          push: true
          tags: torlof/nlp-nvidia-docker-keras:latest
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
